"""Export the deployed XGBoost model to plain C via m2cgen, plus a minimal
C test harness that checks the generated code against a saved Python
prediction to within 1e-4.

m2cgen 0.10.0 has a known incompatibility with XGBoost>=2.0's JSON model
format: `base_score` round-trips as the *string* "5E-1" instead of a float,
and m2cgen's boosting assembler does `1.0 / base_score` expecting a float.
We coerce it back to float before export -- this does not change the
model, only how m2cgen reads a param it already had.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

import numpy as np
import pandas as pd
import xgboost as xgb

ROOT = Path(__file__).resolve().parent.parent
MODELS_DIR = ROOT / "models"
RESULTS_DIR = ROOT / "results"

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s", datefmt="%H:%M:%S")
log = logging.getLogger("export")


def load_deployed_model() -> tuple[xgb.XGBClassifier, list[str]]:
    model = xgb.XGBClassifier()
    model.load_model(str(MODELS_DIR / "model.json"))
    model.set_params(base_score=float(model.get_params()["base_score"]))  # see module docstring
    features = json.loads((MODELS_DIR / "feature_list.json").read_text())
    return model, features


def export_c(model: xgb.XGBClassifier, out_c: Path, out_h: Path, features: list[str]) -> None:
    import m2cgen as m2c

    body = m2c.export_to_c(model)
    out_c.write_text(body)

    header = f"""#ifndef GAITSENSE_MODEL_H
#define GAITSENSE_MODEL_H

/* Auto-generated by src/export.py via m2cgen. Do not hand-edit body in
 * model.c; regenerate instead. Input feature order (index -> name):
 *
{chr(10).join(f' * [{i}] {name}' for i, name in enumerate(features))}
 *
 * output[0] = P(non-faller), output[1] = P(faller). Faller here means
 * self-reported >=2 falls in the year preceding the LTMM recording --
 * this is a retrospective classifier, not a real-time fall predictor.
 */

#define GAITSENSE_N_FEATURES {len(features)}

void score(double * input, double * output);

#endif
"""
    out_h.write_text(header)
    log.info("wrote %s (%d bytes), %s (%d bytes)", out_c, out_c.stat().st_size, out_h, out_h.stat().st_size)


def pick_test_vector(features: list[str]) -> tuple[np.ndarray, dict]:
    df = pd.read_parquet(ROOT / "data" / "cache" / "labeled_features.parquet")
    row = df.iloc[0]
    x = row[features].to_numpy(dtype=float)
    meta = {"subject_id": row["subject_id"], "window_index": int(row["window_index"])}
    return x, meta


def write_test_harness(x: np.ndarray, expected_prob_faller: float, features: list[str], out_dir: Path) -> None:
    vec_c = ", ".join(repr(float(v)) for v in x)
    harness = f"""/* Auto-generated by src/export.py.
 * Feeds one saved feature vector (see model.h for feature order) through
 * the exported model and asserts output[1] (P(faller)) matches the
 * Python-side prediction to within 1e-4.
 *
 * Build:  gcc -O2 -o test_model model.c test_harness.c -lm
 * Run:    ./test_model
 */
#include <stdio.h>
#include <math.h>
#include "model.h"

int main(void) {{
    double input[GAITSENSE_N_FEATURES] = {{ {vec_c} }};
    double output[2];
    score(input, output);

    double expected = {expected_prob_faller!r};
    double diff = fabs(output[1] - expected);

    printf("P(faller) C=%.8f python=%.8f diff=%.8f\\n", output[1], expected, diff);

    if (diff > 1e-4) {{
        fprintf(stderr, "FAIL: prediction mismatch exceeds 1e-4\\n");
        return 1;
    }}
    printf("PASS\\n");
    return 0;
}}
"""
    (out_dir / "test_harness.c").write_text(harness)
    log.info("wrote %s", out_dir / "test_harness.c")


def estimate_flash_footprint(out_c: Path) -> dict:
    src_bytes = out_c.stat().st_size
    # Rough rule of thumb for -O2 on Xtensa/ARM: generated if/else compare
    # chains compile to roughly 1-2x source size in .text (no libc bloat
    # beyond what's already linked). NOT a substitute for compiling with
    # the actual esp-idf toolchain and reading the .map file.
    return {
        "source_bytes": src_bytes,
        "estimated_flash_bytes_low": int(src_bytes * 1.0),
        "estimated_flash_bytes_high": int(src_bytes * 2.0),
        "note": "rough heuristic from source size only -- verify with the real ESP32-S3 toolchain (idf.py size) before trusting it",
    }


def main():
    model, features = load_deployed_model()
    out_c = MODELS_DIR / "model.c"
    out_h = MODELS_DIR / "model.h"
    export_c(model, out_c, out_h, features)

    x, meta = pick_test_vector(features)
    expected = float(model.predict_proba(x.reshape(1, -1))[0, 1])
    log.info("test vector from subject %s window %d -> python P(faller)=%.6f", meta["subject_id"], meta["window_index"], expected)

    write_test_harness(x, expected, features, MODELS_DIR)

    with open(MODELS_DIR / "test_vector.json", "w") as f:
        json.dump({"features": features, "x": x.tolist(), "expected_prob_faller": expected, **meta}, f, indent=2)

    footprint = estimate_flash_footprint(out_c)
    with open(RESULTS_DIR / "export_footprint.json", "w") as f:
        json.dump(footprint, f, indent=2)
    log.info("footprint estimate: %s", footprint)


if __name__ == "__main__":
    main()
