#ifndef GAITSENSE_MODEL_H
#define GAITSENSE_MODEL_H

/* Auto-generated by src/export.py via m2cgen. Do not hand-edit body in
 * model.c; regenerate instead. Input feature order (index -> name):
 *
 * [0] vertical_mean
 * [1] vertical_power_3_8
 * [2] ml_mean
 * [3] ml_rms
 * [4] ap_mean
 * [5] magnitude_mean
 * [6] harmonic_ratio_ml
 * [7] magnitude_rms
 * [8] vertical_skew
 * [9] step_time_mean
 *
 * output[0] = P(non-faller), output[1] = P(faller). Faller here means
 * self-reported >=2 falls in the year preceding the LTMM recording --
 * this is a retrospective classifier, not a real-time fall predictor.
 */

#define GAITSENSE_N_FEATURES 10

void score(double * input, double * output);

#endif
