/* Auto-generated by src/export.py.
 * Feeds one saved feature vector (see model.h for feature order) through
 * the exported model and asserts output[1] (P(faller)) matches the
 * Python-side prediction to within 1e-4.
 *
 * Build:  gcc -O2 -o test_model model.c test_harness.c -lm
 * Run:    ./test_model
 */
#include <stdio.h>
#include <math.h>
#include "model.h"

int main(void) {
    double input[GAITSENSE_N_FEATURES] = { 0.9288409424110217, 0.04309772037594375, -0.1567641907897094, 0.20366053093491396, -0.360220993772042, 1.028462134810079, 2.913342628064344, 1.0668752221988909, 1.0863314481668382, 0.46380952380952384 };
    double output[2];
    score(input, output);

    double expected = 0.012521987780928612;
    double diff = fabs(output[1] - expected);

    printf("P(faller) C=%.8f python=%.8f diff=%.8f\n", output[1], expected, diff);

    if (diff > 1e-4) {
        fprintf(stderr, "FAIL: prediction mismatch exceeds 1e-4\n");
        return 1;
    }
    printf("PASS\n");
    return 0;
}
